var webpack = require('webpack');
var path = require('path')

module.exports = {
    entry: {
        qdb: './src/app'
    },
    output: {
        path: path.resolve('./dist/'),
        filename: '[name].bundle.js'
    },
    cache: true,
    devtool: 'inline-source-map',
    resolve: {
        extensions: ['.ts', '.js', '.tsx', '.jsx'],
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: ['babel-loader', 'ts-loader'],
                exclude: /node_modules/
            },
            {
                test: /\.tsx?$/,
                exclude: /api.ts/, // API is auto-generated by swagger-codegen
                loader: 'tslint-loader',
                options: {
                    typeCheck: true
                },
                enforce: 'pre'
            },
        ],
    },
    plugins: [
        // new webpack.optimize.UglifyJsPlugin([]),
        // new webpack.optimize.DedupePlugin()
    ]
}
