var webpack = require("webpack");
var path = require("path")
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var CopyWebpackPlugin = require("copy-webpack-plugin");
var NodeExternals = require("webpack-node-externals");

module.exports = {
    entry: {
        server: "./src/server"
    },
    output: {
        path: path.resolve("./dist/"),
        filename: "[name].bundle.js"
    },
    cache: true,
    devtool: "inline-source-map",
    target: "node",
    resolve: {
        extensions: [".ts", ".js", ".tsx", ".jsx"],
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: ["babel-loader", "ts-loader"],
                exclude: /node_modules/
            },
            {
                test: /\.tsx?$/,
                exclude: /api.ts/, // API is auto-generated by swagger-codegen
                loader: "tslint-loader",
                options: {
                    typeCheck: true
                },
                enforce: "pre"
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    loader: [
                        "css-loader",
                        "postcss-loader",
                        "sass-loader"
                    ]
                })
            }
        ],
    },
    plugins: [
        // new webpack.optimize.UglifyJsPlugin([]),
        new ExtractTextPlugin({
            filename: "qdb.bundle.css",
            allChunks: true
        }),
        new CopyWebpackPlugin([
            { from: "static" } // Copy contents of /static to /dist/client/
        ])
    ]
}
