var webpack = require("webpack");
var path = require("path")
var NodeExternals = require("webpack-node-externals");

module.exports = {
    entry: {
        server: "./src/server"
    },
    output: {
        path: path.resolve("./dist/"),
        filename: "[name].bundle.js"
    },
    cache: true,
    devtool: "inline-source-map",
    target: "node",
    externals: [NodeExternals()],
    resolve: {
        extensions: [".ts", ".js", ".tsx", ".jsx"],
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: ["babel-loader", "ts-loader"],
                exclude: /node_modules/
            },
            {
                test: /\.tsx?$/,
                exclude: /api.ts/, // API is auto-generated by swagger-codegen
                loader: "tslint-loader",
                options: {
                    typeCheck: true,
                    emitErrors: true,
                    failOnHint: true
                },
                enforce: "pre"
            },
            {
                test: /\.scss?$/,
                loader: "null-loader",
            },
        ],
    },
    plugins: [
        new webpack.DefinePlugin({
            __ASSET_URI_BASE__: node.env.TRAVIS === "true" ? JSON.stringify("https://d3k4bbaes758re.cloudfront.net") : JSON.stringify(""),
        }),
    ],
}
